### ISSUE TITLE
Hello, Could you explain to me please, how can I apply this code on my custom point cloud? 

### ISSUE THREAD

**Issue by Kholoud00** [sparsh-b/Tree-segmentation---LIDAR-data#1]

**Comment by sparsh-b** [comment]
This code should work for any point-cloud dataset.
As for parsing the data, the current data pipeline is set-up to handle a dataset of the format similar to [Oakland 3-D Point Cloud Dataset](https://www.cs.cmu.edu/~vmr/datasets/oakland_3d/cvpr09/doc/). You can try converting your dataset into their format.

Lemme know if u have further questions. :)

**Comment by Kholoud00** [comment]
Thanks. Where should I upload my dataset cause I'm not familiar with C++.

**Comment by sparsh-b** [comment]
If your data is in wrl format, give the path of one of your files here: https://github.com/sparsh-b/Tree-segmentation---LIDAR-data/blob/bff162c22a5ca5e5082d7b811c3f86717c9d81aa/tree_segmenter.cpp#L536

Also, you'll have to change this variable (https://github.com/sparsh-b/Tree-segmentation---LIDAR-data/blob/bff162c22a5ca5e5082d7b811c3f86717c9d81aa/tree_segmenter.cpp#L39) to 1.

Please go through the comments to understand what's happening in the code. Lemme know if you need any further help!

**Comment by Kholoud00** [comment]
Ok. Thanks you.
